### ISSUE TITLE
Python 2.x support?

### ISSUE THREAD

**Issue by rjblake** [ekeih/libtado#2]
Wanted to take a look, but both the Mac and Synology box I use currently use Python 2.7.x and I need these due to other libraries. Is there any specific Python 3.x functionality in use in the library?

**Comment by ekeih** [comment]
Hi,

I think most of the stuff should work fine with python2. I will check this out soon.

Best regards

**Comment by ekeih** [comment]
@rjblake You probably have noticed that I do not longer really develop libtado, so I will close this issue.
If you (or anyone who comes accross this issue) is still interested in libtado you may want to check out the fork of @germainlefebvre4 https://github.com/germainlefebvre4/libtado.
